m{display:none}.v108-manual-form.open{display:grid}.v108-investigation-row-normal{background:color-mix(in srgb,var(--success-soft) 55%,transparent)}.v108-investigation-row-high{background:color-mix(in srgb,var(--danger-soft) 55%,transparent)}.v108-investigation-row-low{background:color-mix(in srgb,#e9f2ff 65%,transparent)}
      .v108-result-flag{display:inline-flex;min-height:25px;align-items:center;padding:3px 8px;border-radius:999px;font-size:.6rem;font-weight:900;text-transform:uppercase}.v108-result-flag.normal{background:var(--success-soft);color:var(--success)}.v108-result-flag.high{background:var(--danger-soft);color:var(--danger)}.v108-result-flag.low{background:#e9f2ff;color:#1358a2}.v108-result-flag.pending{background:var(--warning-soft);color:var(--warning)}
      body.v108-ui #viewRoot .category-tabs{display:flex;flex-wrap:nowrap;gap:6px;overflow-x:auto;scrollbar-width:thin;padding:2px 1px 6px}body.v108-ui #viewRoot .category-tabs [data-action="select-procedure-template"]{flex:0 0 auto;width:auto;max-width:none;white-space:nowrap;overflow:visible;text-overflow:clip;padding-inline:11px}
      .v108-procedure-status{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-bottom:10px}.v108-procedure-status label{cursor:pointer}.v108-procedure-status input{position:absolute;opacity:0;pointer-events:none}.v108-procedure-status span{display:flex;align-items:center;justify-content:center;gap:7px;min-height:44px;border:1px solid var(--line-strong);border-radius:11px;background:var(--surface);font-size:.68rem;font-weight:900}.v108-procedure-status span svg{width:20px;height:20px;flex:0 0 auto}.v108-procedure-status input:checked+span{background:var(--brand);border-color:var(--brand);color:#fff}.v108-procedure-requested{--proc:#a15c00}.v108-procedure-completed{--proc:#078a55}.v108-procedure-badge{display:inline-flex;align-items:center;min-height:24px;padding:3px 8px;border-radius:999px;background:color-mix(in srgb,var(--proc) 13%,var(--surface));color:var(--proc);font-size:.59rem;font-weight:900;text-transform:uppercase;border:1px solid color-mix(in srgb,var(--proc) 26%,transparent)}
      .v108-range-locked .v108-range,.v108-range-locked .v108-tools{opacity:.45;pointer-events:none}
      form[data-form="procedure"][data-procedure-status="requested"] .v108-completed-only{display:none!important}
      .v108-focus-form .field{border:1px solid transparent;border-radius:12px;padding:5px}.v108-focus-form .field:focus-within{border-color:color-mix(in srgb,var(--brand) 22%,var(--line));background:var(--surface-soft)}
      body.v108-ui #viewRoot input,body.v108-ui #viewRoot select,body.v108-ui #viewRoot textarea,body.v108-ui #viewRoot button,body.v108-ui #viewRoot .field{scroll-margin-top:140px}
      body.v108-ui .question-why{display:none!important}body.v108-ui .question-body{padding:20px clamp(14px,3vw,26px)}body.v108-ui .question-body h2{font-size:clamp(1.02rem,2vw,1.35rem);line-height:1.35;margin:8px 0 14px}body.v108-ui .question-options{gap:8px}body.v108-ui .question-options button{min-height:50px;border-radius:13px;font-size:.78rem}
      body.v108-ui .complaint-card{min-height:105px;border-radius:15px}.complaint-icon{background:color-mix(in srgb,var(--brand) 11%,var(--surface));color:var(--brand)}
      @media(max-width:900px){body.v108-ui .workspace{padding:calc(var(--topbar) + 69px) 11px calc(var(--dock) + 62px)!important}#v108FlowBar{margin:-57px 0 10px}.v108-exam-grid{grid-template-columns:1fr}.v108-lab-grid{grid-template-columns:1fr}.quick-dock{width:calc(100vw - 20px)!important}.quick-dock button{min-width:0!important;flex:1}.brand-copy span{display:none!important}}
      @media(max-width:560px){#v108FlowBar{grid-template-columns:40px minmax(0,1fr) 40px;padding:5px}#v108FlowBar .v108-step{min-width:49px;grid-template-columns:1fr;padding:4px 5px}#v108FlowBar .v108-step span{display:none}body.v108-ui .view-header{display:flex;gap:8px}body.v108-ui .view-actions{display:flex;flex-wrap:nowrap;overflow-x:auto;max-width:48%}body.v108-ui .view-actions button{flex:0 0 auto;min-height:39px;padding:6px 9px;font-size:.64rem}body.v108-ui .quick-dock button span:last-child{display:none!important}body.v108-ui .quick-dock button{min-height:43px!important}.v108-lab-actions button{min-width:100%}}
      @media(prefers-reduced-motion:reduce){body.v108-ui *,#v108FlowBar *{animation:none!important;transition:none!important}}
    `;
    document.head.appendChild(style);
  }

  function navColor(routeName) {
    const co