v108NavScrim.open{opacity:1;pointer-events:auto}
      body.v108-ui .view-header{margin-bottom:10px;align-items:center}body.v108-ui .view-header .eyebrow,body.v108-ui .view-header p{display:none!important}body.v108-ui .view-header h1{font-size:clamp(1.25rem,2vw,1.8rem);margin:0;display:flex;align-items:center;gap:9px}
      body.v108-ui .view-header h1 .v108-title-icon{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;color:#fff;background:linear-gradient(135deg,var(--route-color,var(--brand)),color-mix(in srgb,var(--route-color,var(--brand)) 58%,#fff));box-shadow:0 7px 18px color-mix(in srgb,var(--route-color,var(--brand)) 23%,transparent)}
      body.v108-ui .view-header h1 .v108-title-icon svg{width:20px;height:20px}body.v108-ui .view-actions{gap:6px}
      body.v108-ui .card{border-radius:18px;border-color:color-mix(in srgb,var(--brand) 8%,var(--line));box-shadow:0 6px 20px rgba(16,36,62,.055)}
      body.v108-ui .card-header{padding:14px 15px 9px}body.v108-ui .card-header h2,body.v108-ui .card-header h3{font-size:.91rem}body.v108-ui .card-header p{display:none!important}body.v108-ui .card-body{padding:4px 15px 15px}
      body.v108-ui .callout{padding:10px 11px;border-radius:12px}body.v108-ui .callout span{font-size:.62rem;line-height:1.42;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
      body.v108-ui button,body.v108-ui .chip-button{transition:transform var(--v108-fast) ease,background var(--v108-fast) ease,border-color var(--v108-fast) ease,color var(--v108-fast) ease,box-shadow var(--v108-fast) ease}
      body.v108-ui button:active,body.v108-ui .chip-button:active{transform:scale(.985)}
      body.v108-ui .primary-button{background:linear-gradient(135deg,var(--brand),var(--brand-dark));box-shadow:0 7px 16px rgba(11,95,255,.18)}
      body.v108-ui .form-grid,body.v108-ui .grid{gap:12px}body.v108-ui .field{gap:5px}body.v108-ui .field-label,body.v108-ui .field label>span{font-size:.68rem}
      body.v108-ui input,body.v108-ui textarea,body.v108-ui select{border-radius:11px}body.v108-ui textarea{min-height:82px;resize:vertical}
      body.v108-ui .quick-dock{min-height:var(--dock);inset-inline:50%;transform:translateX(-50%);bottom:8px;padding:6px 8px;border-radius:18px;gap:2px;max-width:min(560px,calc(100vw - 20px));width:max-content}
      [dir="rtl"] body.v108-ui .quick-dock{transform:translateX(50%)}body.v108-ui .quick-dock button{min-width:70px;padding:4px 7px;font-size:.52rem}body.v108-ui .quick-dock svg{width:20px;height:20px}
      body.v108-ui .quick-dock button:first-child{color:var(--v108-blue)}body.v108-ui .quick-dock button:nth-child(2){color:var(--v108-purple)}body.v108-ui .quick-dock button:nth-child(4){color:var(--v108-red)}body.v108-ui .quick-dock button:nth-child(5){color:var(--v108-cyan)}
      #v108FlowBar{position:sticky;top:calc(var(--topbar) + 7px);z-index:35;margin:-58px 0 12px;padding:7px;border:1px solid color-mix(in srgb,var(--brand) 16%,var(--line));border-radius:16px;background:color-mix(in srgb,var(--surface) 92%,transparent);backdrop-filter:blur(16px);box-shadow:0 8px 24px rgba(16,36,62,.08);display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:7px}
      #v108FlowBar .v108-step-scroll{display:flex;gap:4px;overflow-x:auto;scrollbar-width:none;padding:1px;max-width:100%}#v108FlowBar .v108-step-scroll::-webkit-scrollbar{display:none}
      #v108FlowBar .v108-step{flex:0 0 auto;min-width:64px;min-height:42px;border:0;border-radius:11px;background:transparent;display:grid;grid-template-columns:18px auto;place-items:center;justify-content:center;gap:5px;padding:5px 8px;color:var(--ink-soft);font-size:.59rem;font-weight:800}
      #v108FlowBar .v108-step svg{width:17px;height:17px;color:var(--step-color,var(--brand))}#v108FlowBar .v108-step.current{background:color-mix(in srgb,var(--step-color,var(--brand)) 11%,var(--surface));color:var(--ink);box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--step-color,var(--brand)) 22%,var(--line))}
      #v108FlowBar .v108-step.done{color:var(--success)}#v108FlowBar .v108-arrow{width:40px;height:40px;border-radius:11px;border:1px solid var(--line);background:var(--surface);display:grid;place-items:center}#v108FlowBar .v108-arrow svg{width:20px;height:20px}
      #v108FlowBar .v108-arrow[disabled]{opacity:.35;pointer-events:none}#v108FlowBar .v108-progress{position:absolute;inset-inline:10px;bottom:2px;height:3px;border-radius:99px;background:var(--line);overflow:hidde